import Head from 'next/head'
import Image from 'next/image'
import { AiOutlineMail } from 'react-icons/ai';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='justify-center content-center gap-4 align-items-center my-20 p-12 shadow-lg max-w mx-auto'>
        <div className="grid grid-cols-2">
          <div>
            <h3>Welcome back ✋</h3>
            <div>
              <h4>Please enter your details</h4>
              <button>Login with Apple</button>
            </div>

            <hr />

            <div className='pt-2'>
              <div class="w-full">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-password">
                  Password
                </label>
                <input class="appearance-none block w-full text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-email" type="email" placeholder="Email" />
                <AiOutlineMail />
                <p class="text-gray-600 text-xs italic">Make it as long and as crazy as you'd like</p>
              </div>
              
              <div class="w-full">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-password">
                  Password
                </label>
                <input class="appearance-none block w-full text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-password" type="password" placeholder="Password" />
                <p class="text-gray-600 text-xs italic">Make it as long and as crazy as you'd like</p>
              </div>
            </div>

            <div className='flex justify-between items-center m-5'>
              <div>
                <input type='checkbox'/> Remember for 30 days
              </div>
              <span className='gap-2'>Forgot password?</span>
            </div>
          </div>
          <Image src='/Fitness_Isometric.svg'
          height={900}
          width={900}
          alt='Your name'
          />
        </div>
      </main>
    </div>
  )
}
